unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g default-shell /opt/homebrew/bin/fish

#Vim-like keys
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind '"'
bind '"' split-window -v -c "#{pane_current_path}"

unbind '%'
bind '%' split-window -h -c "#{pane_current_path}"

